### PR TITLE
cmdwrap: fix build on Windows

### PR DESCRIPTION
**Pull request by kb-equinox**
Currently the build fails to compile on Windows machines because
syscall.Kill is not defined for Windows (reproduce with GOOS=windows
go install ./...). Use an alternative method to terminate the process
on Windows. This is not perfect but it's an improvement over the
current in that it compiles and does what we want.

The current best practice is to avoid directly using the `syscall`
package - the `x/sys/{unix,windows}` packages wrap syscall accesses
in build tags which provide slightly more safety than using
the syscall package directly; see the deprecation notice here.
https://golang.org/pkg/syscall/

Also use a *SysProcAttr on Windows that compiles - it doesn't have the
Setpgid attribute so that was failing to compile.

Noticed this while trying to compile and host a release of justrun on
go.equinox.io.

### CODE REVIEW

**Comment by jmhodges** [comment]
Does this kill the child processes as well on Windows? I don’t see code that does that.

The Setpgid stuff is there to make sure that happens

**Comment by kb-equinox** [comment]
> Does this kill the child processes as well on Windows? I don’t see code that does that.

No... it seems like killing process groups on Windows is kind of a mess, see https://github.com/buildkite/agent/pull/879/files or https://github.com/golang/dep/issues/862#issuecomment-320851740, and I didn't want to add more dependencies or get into the weeds there without a Windows machine.

I can try to do the right thing with the PR here, will need a little more time though.

**Comment by kb-equinox** [comment]
Also this drops compatibility with Go 1.7 and Go 1.8 but those are 2.5 and 3 years old so maybe that's OK!

**Comment by jmhodges** [comment]
Hm, I think if this patch is coming in without testing on a Windows machine, and with a pretty big change in the model that I wrote this project to support, I'm not inclined to take it in. That setpgid stuff is required to make this project work with long-lived processes the way it does.

**Pull request closed without merging**
